### ISSUE TITLE
Improve Accuracy by Exploring Alternative Machine Learning Models

### ISSUE THREAD

**Issue by ayesha-119** [Rakesh9100/ML-Project-Drug-Review-Dataset#10] opened 2023-05-20 08:31 UTC
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As a participant in the Girls Script Summer of Code (GSSoC) program, I have noticed an opportunity to enhance the accuracy of the machine learning model by exploring alternative models. Although Linear Regression, Logistic Regression, Perceptron, and Decision Tree Classifiers have been applied, I believe that considering additional models can help us achieve higher predictive performance.

To address this, I propose the following steps:

1. **Research and Evaluate Alternative Models:** Conduct a thorough investigation of various machine learning models suitable for the given task, such as Random Forest, Support Vector Machines (SVM), Gradient Boosting Models (e.g., XGBoost, LightGBM), Neural Networks (e.g., using TensorFlow or PyTorch), Naive Bayes, K-Nearest Neighbors (KNN), and others. Compare their strengths, weaknesses, and suitability for the dataset.

2. **Implement and Train Alternative Models:** Select a subset of promising models and implement them in the project. Utilize appropriate libraries and frameworks for each model and train them on the Drug Review Dataset, following best practices and considering proper hyperparameter tuning techniques.

3. **Performance Evaluation and Comparison:** Evaluate the performance of the alternative models using appropriate evaluation metrics (e.g., accuracy, precision, recall, F1-score) and compare them against the existing models. Identify the models that show improved accuracy or other desirable performance characteristics.

4. **Fine-tuning and Model Ensemble:** If a specific alternative model outperforms the existing ones, consider further fine-tuning its hyperparameters to maximize its potential. Additionally, explore the possibility of creating a model ensemble by combining the strengths of multiple models to achieve even higher accuracy.

5. **Documentation and Reporting:** Document the findings, including the performance comparison, insights gained, and recommendations for selecting the most accurate model(s). Provide clear instructions on integrating the recommended models into the project and any modifications required for the existing implementation.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by varsha089** [comment] 2023-05-20 12:39
Please assign this issue to me under Gssoc 2023.

**Comment by ayesha-firdaus** [comment] 2023-05-20 16:06
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by UditSharma9999** [comment] 2023-05-20 16:54
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by sijalalyy** [comment] 2023-05-21 14:40
I am GSSOC 23 contributor assign this to me i want to work on this

**Comment by Rakesh9100** [comment] 2023-05-22 17:47
@ayesha-119 Assigning you, Go ahead

**Comment by Rakesh9100** [comment] 2023-05-26 21:22
@ayesha-firdaus @UditSharma9999 Do you want to work

**Comment by ayesha-119** [comment] 2023-05-26 21:24
> 

Haven't you assigned this issue to me? @Rakesh9100

**Comment by Rakesh9100** [comment] 2023-05-26 21:26
@ayesha-119 I have assigned you but it's been 4 days and no update from your side. If you are working pls tell me.

**Comment by ayesha-119** [comment] 2023-05-26 21:27
> @ayesha-119 I have assigned you but it's been 4 days and no update from your side. If you are working pls tell me.

Yeah I'm 

> @ayesha-119 I have assigned you but it's been 4 days and no update from your side. If you are working pls tell me.

Yes I'm working on it.

**Comment by Rakesh9100** [comment] 2023-05-26 21:28
Okay then what the status? When will you create PR? @ayesha-119

**Comment by ayesha-119** [comment] 2023-05-26 21:39
> Okay then what the status? When will you create PR? @ayesha-119
tomorrow or the day after that

**Comment by Rakesh9100** [comment] 2023-05-26 21:39
Okay

**Comment by jahnvisahni31** [comment] 2023-05-29 16:57
Hi, @Rakesh9100 I would like to contribute. Please assign the task to me under GSSOC'23.

**Comment by Mimi97-aqua** [comment] 2023-05-30 19:22
I am a GSSOC2023 contributor and would like for this to be assigned to me please.

**Comment by Rakesh9100** [comment] 2023-06-02 17:40
@ayesha-firdaus @sijalalyy Would you like to work? If yes describe in brief the work you will do.

**Comment by sijalalyy** [comment] 2023-06-02 17:55
Yes, I want to work on this issue. Many alternative ML models like KNN, SVM, Random Tree can be used to improve accuracy.

**Comment by Rakesh9100** [comment] 2023-06-02 18:05
Proceed @sijalalyy Assigned

**Comment by sijalalyy** [comment] 2023-06-02 18:07
Ok. Thankyou.

**Comment by Rakesh9100** [comment] 2023-06-11 19:19
@sijalalyy Update pls

**Comment by sijalalyy** [comment] 2023-06-11 19:47
> @sijalalyy Update pls

70% done, going to create PR in 2 days, hopefully by wednesday

**Comment by sijalalyy** [comment] 2023-06-15 13:37
@Rakesh9100 sorry for the delay because of unexpected electricity and internet issues due to cyclone biparjoy, i will create PR in two days. Thankyou.

**Comment by Rakesh9100** [comment] 2023-06-20 10:04
Any Update finally @sijalalyy

**Comment by sijalalyy** [comment] 2023-06-20 10:37
yes, i will create PR today

**Closed as completed** 2023-06-26 19:23 UTC
Labels: duplicate 🔁
