### ISSUE TITLE
Implement Ensemble Model of Sparse Multi-Layer Perceptron

### ISSUE THREAD

**Issue by elucidator8918** [Rakesh9100/ML-Project-Drug-Review-Dataset#9] opened 2023-05-20 08:29 UTC
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hello, I am Siddhant Dutta - I am a GSSOC'23 Contributor. I have done a similar task regarding this topic and I think I would be able to contribute greatly to this open-source project. This is my resume - [Resume](https://drive.google.com/file/d/1iRPv-76FDxEyo-7QdmxDp3le7DEabK-Q/view?usp=sharing)

Would Start Working on the Project - Whenever the Project is assigned to me
Would be done with it - 1month after the project is assigned to me

Tasks I will do - 

1) To implement an ensemble model of sparse multi-layer perceptrons (MLPs) to analyze and evaluate the effectiveness of different drugs in treating specific medical conditions.

2) These models have proved themselves to work and give a high accuracy for text-based datasets where the text corpus is huge.

3) The main part of the project lies in the feature engineering section, hence I would provide a complete end-to-end pipeline in Python.

4) Will do a complete EDA in the initial stage and then would apply different kinds of strategies such as the creation of sparse embeddings and best feature selection to improve the final SMLP model.

5) After Feature engineering, I would also try out different models such as LightGBM & CatBoost and would test their accuracy of them as well.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by ayesha-firdaus** [comment] 2023-05-20 16:05
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by UditSharma9999** [comment] 2023-05-20 16:54
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by Rakesh9100** [comment] 2023-05-22 17:43
@elucidator8918 Assigning you, Proceed

**Closed as completed** 2023-05-26 21:21 UTC
Labels: invalid ❌, wontfix 🚫
