### ISSUE TITLE
Change perceptron model to Multi Layer Perceptron Classifier

### ISSUE THREAD

**Issue by arijitghosal03** [Rakesh9100/ML-Project-Drug-Review-Dataset#5] opened 2023-05-20 06:22 UTC
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The perceptron used in this ML model is a single layer neuron with much lesser efficiency of ~0.14
I would like to explore more the effectiveness of neural network model and add some hidden layers between input and output through scikit learn neural network model.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by ayesha-firdaus** [comment] 2023-05-20 16:05
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by UditSharma9999** [comment] 2023-05-20 16:54
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by Abhinavcode13** [comment] 2023-05-21 04:18
Can you assign this issue to me under Gssoc 23 , will come up with efficient solution @Rakesh9100 !!

**Comment by Rakesh9100** [comment] 2023-05-22 17:31
Don't create PR unless you are assigned an issue. Pls abide by the rules of Open Source with good practices. Create a new PR and in a new branch.
Assigning you @arijitghosal03

**Closed as completed** 2023-05-23 18:25 UTC
Labels: enhancement ✨, gssoc23, level2
